add_vhdl_file sources_1 MERGE_SORTER ../../ip/argsort_axi_0.6/src/MERGE_SORTER/word.vhd
add_vhdl_file sources_1 MERGE_SORTER ../../ip/argsort_axi_0.6/src/MERGE_SORTER/core_components.vhd
add_vhdl_file sources_1 MERGE_SORTER ../../ip/argsort_axi_0.6/src/MERGE_SORTER/interface.vhd
add_vhdl_file sources_1 MERGE_SORTER ../../ip/argsort_axi_0.6/src/MERGE_SORTER/word_compare.vhd
add_vhdl_file sources_1 MERGE_SORTER ../../ip/argsort_axi_0.6/src/MERGE_SORTER/argsort_axi_components.vhd
add_vhdl_file sources_1 MERGE_SORTER ../../ip/argsort_axi_0.6/src/MERGE_SORTER/argsort_reader.vhd
add_vhdl_file sources_1 MERGE_SORTER ../../ip/argsort_axi_0.6/src/MERGE_SORTER/argsort_writer.vhd
add_vhdl_file sources_1 MERGE_SORTER ../../ip/argsort_axi_0.6/src/MERGE_SORTER/interface_components.vhd
add_vhdl_file sources_1 MERGE_SORTER ../../ip/argsort_axi_0.6/src/MERGE_SORTER/merge_reader.vhd
add_vhdl_file sources_1 MERGE_SORTER ../../ip/argsort_axi_0.6/src/MERGE_SORTER/merge_sorter_node.vhd
add_vhdl_file sources_1 MERGE_SORTER ../../ip/argsort_axi_0.6/src/MERGE_SORTER/merge_writer.vhd
add_vhdl_file sources_1 MERGE_SORTER ../../ip/argsort_axi_0.6/src/MERGE_SORTER/word_queue.vhd
add_vhdl_file sources_1 MERGE_SORTER ../../ip/argsort_axi_0.6/src/MERGE_SORTER/argsort_axi_reader.vhd
add_vhdl_file sources_1 MERGE_SORTER ../../ip/argsort_axi_0.6/src/MERGE_SORTER/argsort_axi_writer.vhd
add_vhdl_file sources_1 MERGE_SORTER ../../ip/argsort_axi_0.6/src/MERGE_SORTER/core_intake_fifo.vhd
add_vhdl_file sources_1 MERGE_SORTER ../../ip/argsort_axi_0.6/src/MERGE_SORTER/core_stream_intake.vhd
add_vhdl_file sources_1 MERGE_SORTER ../../ip/argsort_axi_0.6/src/MERGE_SORTER/drop_none.vhd
add_vhdl_file sources_1 MERGE_SORTER ../../ip/argsort_axi_0.6/src/MERGE_SORTER/interface_controller.vhd
add_vhdl_file sources_1 MERGE_SORTER ../../ip/argsort_axi_0.6/src/MERGE_SORTER/merge_axi_reader.vhd
add_vhdl_file sources_1 MERGE_SORTER ../../ip/argsort_axi_0.6/src/MERGE_SORTER/merge_axi_writer.vhd
add_vhdl_file sources_1 MERGE_SORTER ../../ip/argsort_axi_0.6/src/MERGE_SORTER/merge_sorter_tree.vhd
add_vhdl_file sources_1 MERGE_SORTER ../../ip/argsort_axi_0.6/src/MERGE_SORTER/argsort_axi_interface.vhd
add_vhdl_file sources_1 MERGE_SORTER ../../ip/argsort_axi_0.6/src/MERGE_SORTER/merge_sorter_core.vhd
add_vhdl_file sources_1 MERGE_SORTER ../../ip/argsort_axi_0.6/src/MERGE_SORTER/argsort_axi.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/components.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/queue_register.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/reducer.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/axi4_components.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/axi4_data_port.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/chopper.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/float_intake_valve.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/float_outlet_valve.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/pool_outlet_port.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/axi4_data_outlet_port.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/count_down_register.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/count_up_register.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/delay_adjuster.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/delay_register.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/float_intake_manifold_valve.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/float_outlet_manifold_valve.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/pump_components.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/pump_control_register.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/syncronizer.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/syncronizer_input_pending_register.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/axi4_master_address_channel_controller.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/axi4_master_transfer_queue.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/axi4_register_read_interface.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/axi4_register_write_interface.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/pool_intake_port.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/pump_controller_intake_side.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/pump_controller_outlet_side.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/pump_flow_syncronizer.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/queue_arbiter.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/queue_receiver.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/register_access_decoder.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/register_access_syncronizer.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/sdpram.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/axi4_master_read_interface.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/axi4_master_write_interface.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/axi4_register_interface.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/axi4_types.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/pump_stream_intake_controller.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/pump_stream_outlet_controller.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/queue_arbiter_integer_arch.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/queue_arbiter_one_hot_arch.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/queue_tree_arbiter.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/register_access_adapter.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/sdpram_altera_auto_select.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/sdpram_model.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/sdpram_xilinx_auto_select.vhd
add_vhdl_file sources_1 PIPEWORK ../../ip/argsort_axi_0.6/src/PIPEWORK/sdpram_xilinx_ultrascale_auto_select.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../Merge_Sorter/Dummy_Plug/src/main/vhdl/core/util.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../Merge_Sorter/Dummy_Plug/src/main/vhdl/axi4/axi4_types.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../Merge_Sorter/Dummy_Plug/src/main/vhdl/core/reader.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../Merge_Sorter/Dummy_Plug/src/main/vhdl/core/sync.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../Merge_Sorter/Dummy_Plug/src/main/vhdl/core/vocal.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../Merge_Sorter/Dummy_Plug/src/main/vhdl/core/core.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../Merge_Sorter/Dummy_Plug/src/main/vhdl/axi4/axi4_core.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../Merge_Sorter/Dummy_Plug/src/main/vhdl/axi4/axi4_channel_player.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../Merge_Sorter/Dummy_Plug/src/main/vhdl/axi4/axi4_master_player.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../Merge_Sorter/Dummy_Plug/src/main/vhdl/axi4/axi4_memory_player.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../Merge_Sorter/Dummy_Plug/src/main/vhdl/axi4/axi4_models.vhd
add_vhdl_file sim_1     DUMMY_PLUG ../../Merge_Sorter/Dummy_Plug/src/main/vhdl/core/marchal.vhd
add_vhdl_file sim_1     WORK ../../Merge_Sorter/src/test/vhdl/argsort_axi_test_bench.vhd
