add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/axi4/axi4_types.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/components/components.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/components/queue_register.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/components/reducer.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/axi4/axi4_components.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/axi4/axi4_data_port.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/components/chopper.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/components/float_intake_valve.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/components/float_outlet_valve.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/components/pool_outlet_port.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/axi4/axi4_data_outlet_port.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/components/count_down_register.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/components/count_up_register.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/components/delay_adjuster.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/components/delay_register.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/components/float_intake_manifold_valve.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/components/float_outlet_manifold_valve.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/components/syncronizer.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/components/syncronizer_input_pending_register.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/pump/pump_components.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/pump/pump_control_register.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/axi4/axi4_master_address_channel_controller.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/axi4/axi4_master_transfer_queue.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/axi4/axi4_register_read_interface.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/axi4/axi4_register_write_interface.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/components/pipeline_register_controller.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/components/pool_intake_port.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/components/queue_arbiter.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/components/queue_receiver.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/components/register_access_decoder.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/components/register_access_syncronizer.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/components/sdpram.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/pump/pump_controller_intake_side.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/pump/pump_controller_outlet_side.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/pump/pump_flow_syncronizer.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/axi4/axi4_master_read_interface.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/axi4/axi4_master_write_interface.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/axi4/axi4_register_interface.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/components/pipeline_register.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/components/queue_arbiter_one_hot_arch.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/components/queue_tree_arbiter.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/components/register_access_adapter.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/components/sdpram_altera_auto_select.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/components/sdpram_model.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/components/sdpram_xilinx_auto_select.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/components/sdpram_xilinx_ultrascale_auto_select.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/pump/pump_stream_intake_controller.vhd
add_vhdl_file sources_1 PIPEWORK ../Merge_Sorter/PipeWork/src/pump/pump_stream_outlet_controller.vhd
add_vhdl_file sources_1 MERGE_SORTER ../Merge_Sorter/src/main/vhdl/core/word.vhd
add_vhdl_file sources_1 MERGE_SORTER ../Merge_Sorter/src/main/vhdl/core/sorting_network.vhd
add_vhdl_file sources_1 MERGE_SORTER ../Merge_Sorter/src/main/vhdl/core/core_components.vhd
add_vhdl_file sources_1 MERGE_SORTER ../Merge_Sorter/src/main/vhdl/core/word_compare.vhd
add_vhdl_file sources_1 MERGE_SORTER ../Merge_Sorter/src/main/vhdl/core/sorting_network_core.vhd
add_vhdl_file sources_1 MERGE_SORTER ../Merge_Sorter/src/main/vhdl/core/word_queue.vhd
add_vhdl_file sources_1 MERGE_SORTER ../Merge_Sorter/src/main/vhdl/interface/interface.vhd
add_vhdl_file sources_1 MERGE_SORTER ../Merge_Sorter/src/main/vhdl/core/merge_sorter_node.vhd
add_vhdl_file sources_1 MERGE_SORTER ../Merge_Sorter/src/main/vhdl/core/word_reducer.vhd
add_vhdl_file sources_1 MERGE_SORTER ../Merge_Sorter/src/main/vhdl/examples/argsort_axi/argsort_axi_components.vhd
add_vhdl_file sources_1 MERGE_SORTER ../Merge_Sorter/src/main/vhdl/examples/argsort_axi/argsort_reader.vhd
add_vhdl_file sources_1 MERGE_SORTER ../Merge_Sorter/src/main/vhdl/examples/argsort_axi/argsort_writer.vhd
add_vhdl_file sources_1 MERGE_SORTER ../Merge_Sorter/src/main/vhdl/interface/interface_components.vhd
add_vhdl_file sources_1 MERGE_SORTER ../Merge_Sorter/src/main/vhdl/interface/merge_reader.vhd
add_vhdl_file sources_1 MERGE_SORTER ../Merge_Sorter/src/main/vhdl/interface/merge_writer.vhd
add_vhdl_file sources_1 MERGE_SORTER ../Merge_Sorter/src/main/vhdl/core/core_intake_fifo.vhd
add_vhdl_file sources_1 MERGE_SORTER ../Merge_Sorter/src/main/vhdl/core/core_stream_intake.vhd
add_vhdl_file sources_1 MERGE_SORTER ../Merge_Sorter/src/main/vhdl/core/drop_none.vhd
add_vhdl_file sources_1 MERGE_SORTER ../Merge_Sorter/src/main/vhdl/core/merge_sorter_tree.vhd
add_vhdl_file sources_1 MERGE_SORTER ../Merge_Sorter/src/main/vhdl/examples/argsort_axi/argsort_axi_reader.vhd
add_vhdl_file sources_1 MERGE_SORTER ../Merge_Sorter/src/main/vhdl/examples/argsort_axi/argsort_axi_writer.vhd
add_vhdl_file sources_1 MERGE_SORTER ../Merge_Sorter/src/main/vhdl/interface/interface_controller.vhd
add_vhdl_file sources_1 MERGE_SORTER ../Merge_Sorter/src/main/vhdl/interface/merge_axi_reader.vhd
add_vhdl_file sources_1 MERGE_SORTER ../Merge_Sorter/src/main/vhdl/interface/merge_axi_writer.vhd
add_vhdl_file sources_1 MERGE_SORTER ../Merge_Sorter/src/main/vhdl/core/merge_sorter_core.vhd
add_vhdl_file sources_1 MERGE_SORTER ../Merge_Sorter/src/main/vhdl/examples/argsort_axi/argsort_axi_interface.vhd
add_vhdl_file sources_1 MERGE_SORTER ../Merge_Sorter/src/main/vhdl/examples/argsort_axi/argsort_axi.vhd
